### ISSUE TITLE
[RFC] - fix ACL on update

### ISSUE THREAD

**Issue by alikon** [joomla-projects/gsoc16_improved-multi-lingual#101]
this snippet of code for clone from the com_content  "core.admin", "core.manage"  rules  when updating

``` php

$assetRules = JAccess::getAssetRules('com_content');
$assetData  = $assetRules->getData();
$rules = new JRegistry();           
$rules->loadString($assetData['core.admin']);  
$core_admin =$rules->__toString();
$rules = new JRegistry();           
$rules->loadString($assetData['core.manage']);  
$core_manage=$rules->__toString();

$cloned_rules = '{"core.admin":'.$core_admin.','. '"core.manage":'.$core_manage.'}';
//echo '{"core.admin":'.$core_admin.','. '"core.manage":'.$core_manage.'}';
```

so in  administrator/components/com_admin/script.php

``` php
if ($component === 'com_associations')
{
     $asset->rules = $cloned_rules';
}
```

for sure can be done more more better   ....
any feedback....

**Comment by andrepereiradasilva** [comment]
so you are adding the same groups for Administrator and Manager as the exisitng for com_content? 

it could be one way to solve the issue.
Anyway i think you are doing that in all joomla updates right? So it will change on each update, or am i wrong?

@infograf768 @jreys your opinion here please.

**Comment by alikon** [comment]
> so you are adding the same groups for Administrator and Manager as the exisitng for com_content?

yes

> Anyway i think you are doing that in all joomla updates right? So it will change on each update, or am i wrong?

wrong
it will be done only on the first update i.e only when the com_associations is installed for the 1st time

see
https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_admin/script.php#L1604

**Comment by andrepereiradasilva** [comment]
ok then

**Comment by andrepereiradasilva** [comment]
closed as we have a PR
