### ISSUE TITLE
Review project timeline from 1º july to end

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#11]
As meeting on 20/06/2016 make the first revision of project timeline (detailed).

**Comment by jreys** [comment]
First draft:

week 1:
    - fetch all components to filter list
    - implement filter list with links to the side-by-side
    (these are the remaining tasks from first code period)

week 2:
    - implement change languages in the side by side
    - create a new article (or contact, etc.) by changing language

week 3:
    - auto-generate ACL user groups equal to content languages
    - enforce ACL

week 4:
    - implement validation (if not already done)
    - implementing copy feature by auto-filling fields with reference data

week 5:
    - implementing "help" content and config options

last weeks and days:
    - testing

**Comment by andrepereiradasilva** [comment]
not full review. just a comment

> - auto-generate ACL user groups equal to content languages

Not needed. JM and i are working on implementing ACL on com_languages https://github.com/infograf768/joomla-cms/pull/30.

i think the plan (JM confirm) is for this new ACL action `language.permission` to be used for all associations.

so com_associations just need the basic ACL core.admin and core.manage which to autogenerate i just add to com_admin script.

See `updateAssets()` method in joomla update script https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1575

**Comment by andrepereiradasilva** [comment]
another comment:
in "week 5:" you need to add the new componet to install and update script and test it all works well on joomla update and joomla new install.

**Comment by andrepereiradasilva** [comment]
this are (at least) your "last weeks and days:" tasks (besides testing)
see https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/9

**Comment by jreys** [comment]
got it @andrepereiradasilva !

**Comment by infograf768** [comment]
> i think the plan (JM confirm) is for this new ACL action language.permission to be used for all associations.

Indeed and as we will need a new contentlanguage field type (for example contentlanguageassoc) [See PR], as we can't change atm the general one, we will create it. It will have to be placed in com_associations/models/fields/. It will not include language ALL.

**Comment by jreys** [comment]
Update from last meeting:

week 1 (2016/07/03 - 2016/07/09):
- Fetch all components to filter list
- Implement filter list with links to the side-by-side

week 2 (2016/07/10 - 2016/07/16):
- Implement save on side by side
  (these weeks are the remaining tasks from first code period)

week 3 (2016/07/17 - 2016/07/23):
- Enforce com_languages + component ACL
- Implement server side validation (if not already done)

week 4 (2016/07/24 - 2016/07/30):
- Implement client side validation (if not already done)
- Implement block changing reference language (just view)
- Implement copy feature by auto-filling fields with reference data
- Implement change languages in the side by side

week 5 (2016/07/31 - 2016/08/06):
- Create a new item (article, contact, etc.) by changing language or directly on list view
- Create a new section (category, etc.) by changing language or directly on list view

week 6 (2016/08/07 - 2016/08/13):
- Besides travis CS, needs to conform with all Joomla coding styles (XML, PHP, HTML, etc)
- Component code should use the API as much as possible
- Component code should reuse code as much as possible
- Component needs to work with all Joomla 3.x supported db versions (mysql, postgresql, sqlazure)
- Component needs to work with all Joomla 3.x supported php versions (5.3.10+)
- Component needs to work with new install AND upgrade process

week 7 and last days (2016/08/14 - end):
- Implement "help" content.
- Language strings need to be alpha ordered in ini files.
- Javascript/PHP Error catching
- Graphical and usability review
- Final tests and corrections

**Comment by alikon** [comment]
ok so lets start ....
:yum:

**Comment by andrepereiradasilva** [comment]
task finished
