### ISSUE TITLE
Discuss component arquitecture

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#114]
Placeholder to discuss component arquitecture in the light of the comments in https://github.com/joomla/joomla-cms/pull/11623.

**Comment by infograf768** [comment]
@jreys 
I think we should go with the new helper in the extension back-end.
First aspect to define: what exactly should it contain that would be fetched by com_associations own helper to include the extension in com_associations?
I mean the minimum required and some stuff that would or not exist which would change some UI in com_associations (like save2copy with a generatenewtitle() for example)

**Comment by alikon** [comment]
@jreys for reference look at how com_categories do for manage items count https://github.com/joomla/joomla-cms/pull/9429
or https://github.com/joomla/joomla-cms/pull/10895 do for tags

**Comment by andrepereiradasilva** [comment]
For reference, any change made:
- needs to support component multi-item types per component
- needs to support component multi-item types categories per component
- needs to respect component multi-item types ACL
- needs to respect component multi-item types checkin/checkout
