### ISSUE TITLE
scripts and css should be in the template file, not in the view file

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#14]
This ones https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/views/association/view.html.php#L99-L132

**Comment by jreys** [comment]
Fix here: https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/16

**Comment by andrepereiradasilva** [comment]
closed as we have a PR to test. 
See https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/16
