### ISSUE TITLE
Completion tasks of side-by-side

### ISSUE THREAD

**Issue by jreys** [joomla-projects/gsoc16_improved-multi-lingual#25]
I created this issue to better organise my work on the side-by-side, it will list the tasks and the completion status.
- [x] Language switcher 
- [x] Save new item
- [x] Save associated item
- [x] Checkin on close
- [x] Disable language selector on ref and target
- [ ] Select Custom Target
- [ ] Copy button
- [x] ACL
- [x] Code Style

**Comment by andrepereiradasilva** [comment]
Please add this tasks for **After merge PR**:
- 3º party support review
- Better integration with list view. ex: direct links to language association edit (also for list view)
- Code uniformization with core, corrections and optimizations
- Heavy tests with all possible scenarios (including ACL scenarios)

**Comment by andrepereiradasilva** [comment]
- Hide "Associations" tab on reference AND target
- Disable language selector on reference AND target

**Comment by andrepereiradasilva** [comment]
This one is an idea:
- Add reference language Selector? (to discuss - @infograf768)

**Comment by jreys** [comment]
@andrepereiradasilva , 

> Please add this tasks for After merge PR:
> - 3º party support review
> - Better integration with list view. ex: direct links to language association edit (also for list view)
> - Code uniformization with core, corrections and optimizations
> - Heavy tests with all possible scenarios

I only created this issue concerning the side-by-side PR, that is for later :wink: but will take that into account

**Comment by andrepereiradasilva** [comment]
ok, just to get this _on record_

**Comment by andrepereiradasilva** [comment]
one more as talked before:

- Correct bug in selecting language

> "- Select language -" option is loading */administrator/index.php?option=com_content&view=article&extension=&task=article.edit&layout=edit&tmpl=component&id=undefined* when it should not load anything (no iframe). notice the id=undefined

**Comment by andrepereiradasilva** [comment]
and another one task:
- Add keepalive behaviouro to side by side main page so it doesn't expire on session expire

**Comment by andrepereiradasilva** [comment]
For reference posted by nicola some days ago 

![image](https://cloud.githubusercontent.com/assets/9630530/17152603/69a55842-5370-11e6-8d47-71bda7f9c881.png)

**Comment by jreys** [comment]
Adding task for after:
![image](https://cloud.githubusercontent.com/assets/16468676/17185762/4d74f00a-542a-11e6-8503-abb6fe0c498a.png)

**Comment by jreys** [comment]
Adding task:
- Edit show/hide reference button with language strings and proper JS

**Comment by andrepereiradasilva** [comment]
closing this as will be replace by a  new issue
