### ISSUE TITLE
Non core extensions list that uses associations

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#29]
The propose is to list non core extensions that support associations so we can use them for tests.

Core Supported:
- com_weblinks (just categories)
  
  https://github.com/joomla-extensions/weblinks/releases/download/3.5.0/pkg-weblinks-3.5.0.zip

3º Party:
- Sermon speaker
  
  http://www.sermonspeaker.net/download/sermonspeaker-component/sermonspeaker-component-5-5-2/pkg_sermonspeaker-zip.zip

**Comment by alikon** [comment]
Sermon Speaker:  http://www.sermonspeaker.net/download/sermonspeaker-component.html

**Comment by andrepereiradasilva** [comment]
hum, installed that componet and only categories were discovered

**Comment by infograf768** [comment]
See: https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/70

**Comment by ggppdk** [comment]
@andrepereiradasilva 

sorry for late response, i will test too

**Comment by andrepereiradasilva** [comment]
is it possible for us to also test your extension?

**Comment by andrepereiradasilva** [comment]
since nobosy else sent an extension to test. i'm going to close this.
