### ISSUE TITLE
php notice in side by side view

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#31]
not much to say ...

![image](https://cloud.githubusercontent.com/assets/9630530/17213771/aefbbdb0-54cd-11e6-8fa0-8db98776e362.png)

**Comment by jreys** [comment]
I'll also fix the problem that the switcher is now loading the reference language too.

**Comment by andrepereiradasilva** [comment]
closed as solved by https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/34
