### ISSUE TITLE
AssociationsHelper::loadLanguageFiles really needed?

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#32]
Please check if this is really needed. If not remove:
- https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/helpers/associations.php#L256-L324
- https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_associations/views/association/view.html.php#L57

**Comment by jreys** [comment]
Tested, not needed, will PR

**Comment by andrepereiradasilva** [comment]
solved by https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/35
