### ISSUE TITLE
Menu item edit view association problems

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#43]
- does not use an id field ??? (PR https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/46)
- does not use modals for associations!

**Comment by jreys** [comment]
> - does not use an id field ???

Checkin on menus not working because of this...

**Comment by andrepereiradasilva** [comment]
i think we need to add it to the core ...

**Comment by andrepereiradasilva** [comment]
i'm gona close this, because it works fine.
But we still need to make the PR to the code ...
