### ISSUE TITLE
Check if requirements to use component are fullfilled

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#6]
To use com_associations the site needs to be multilangual.
So we need a check on component views.

Basicly we need to check if language filter plugin is enabled.
Something like this is the view file.

``` php
if (!JLanguageMultilang::isEnabled())
{
JFactory::getApplication->enqueueMessage('The Language Filter System Plugin is disabled. It needs to be enabled for this component to work.', 'warning');
}
```

Note: This message needs to be translatable and should have a link directly to language filter plugin.

See a PR for similiar message in the com_redirect: https://github.com/joomla/joomla-cms/pull/10688

Also we need to check if associations inside the language filter plugin are enabled.

**Comment by infograf768** [comment]
The other check is
`JLanguageAssociations::isEnabled()`
So both should be used.

**Comment by infograf768** [comment]
In fact, checking for  `JLanguageAssociations::isEnabled()` also checks for `JLanguageMultilang::isEnabled()`
so it needs only the first one.

See
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/language/associations.php#L132-L158

**Comment by andrepereiradasilva** [comment]
done!
