### ISSUE TITLE
Testing 3rd party component sermonspeaker

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/gsoc16_improved-multi-lingual#70]
I first installed it and got 2 errors:
[08-Aug-2016 07:54:48 UTC] PHP Notice: Undefined index: associations in /Applications/MAMP/htdocs/gsocmulti/administrator/components/com_categories/models/category.php on line 575 
[08-Aug-2016 07:54:48 UTC] PHP Warning: constant(): Couldn't find constant JPATH_ in /Applications/MAMP/htdocs/gsocmulti/libraries/cms/installer/adapter/module.php on line 209

I then tested Associations list:
I only could select Categories and had an unstranslated string:
`COM_SERMONSPEAKER_CATEGORIES`

=> This means imho that we should, when we have categories for a component, force the string to be
`COM_CATEGORIES="Categories"` and not rely on the component specific string as it may not exist.
Change should be line 103 of `ROOT/administrator/components/com_associations/models/fields/associatedcomponent.php`
I.e. chnage
`$languageKey           = JText::_(strtoupper($cp->realcomponent) . '_CATEGORIES');`
to
`$languageKey           = JText::_('COM_CATEGORIES');`

=>Although the component has an association site helper including various views, I did not get them in the dropdown...

**Comment by infograf768** [comment]
I could create and associate categories

**Comment by jreys** [comment]
hmmmm, that sounds a little "hacky", I think we should load the component's language strings, in fact it's being done in
`ROOT/administrator/components/com_associations/helpers/associations.php`
(line 177)
but for some reason, it's not being loaded

**Comment by infograf768** [comment]
The component strings ARE loaded.
But he does not have that string in its ini file...

**Comment by jreys** [comment]
I see now, then I agree, if lang string is not present, we use COM_CATEGORIES instead, this keeps flexibility in case an extension wants to give another name to it

**Comment by infograf768** [comment]
We have a specific code to check if a lang string is present or not
looking now

**Comment by infograf768** [comment]
if ($lang->hasKey( etc.

**Comment by infograf768** [comment]
i.e.

```
            // Check if component uses categories with associations. Add category option to select box if so.
            if ($cp->enabled && $cp->associations->supportCategories)
            {
                $lang = JFactory::getLanguage();

                // Check if component ini file has a specific key
                if ($lang->hasKey($cp->realcomponent . '_CATEGORIES'))
                {
                    $languageKey = JText::_(strtoupper($cp->realcomponent) . '_CATEGORIES');
                }
                else
                {
                    $languageKey = JText::_('COM_CATEGORIES');
                }

                $options[$cp->title][] = JHtml::_('select.option', 'com_categories.category:' . $cp->realcomponent, $languageKey);
            }
        }
```

**Comment by infograf768** [comment]
Except that we do not load com_categories.ini any more in the list...
So, maybe we need to create a specific com_associations string
`COM_ASSOCIATIONS_CATEGORIES` or something

**Comment by infograf768** [comment]
Concerning the items, sermonspeaker does not have the `$associationsContext` and `$typealias` in it models.
After adding these in `ROOT/administrator/components/com_sermonspeaker/models/speaker.php`
as

```
    /**
     * The type alias for this content type.
     *
     * @var      string
     * @since    3.2
     */
    public $typeAlias = 'com_sermonspeaker.speaker';

    /**
     * The context used for the associations table
     *
     * @var string
     * @since    3.4.4
     */
    protected $associationsContext = 'com_sermonspeaker.item';
```

I get this in the dropdown
![screen shot 2016-08-08 at 11 15 46](https://cloud.githubusercontent.com/assets/869724/17475081/822284d8-5d59-11e6-9f5d-fd38f868eccc.png)

Tried to associate item

I got this as result:

![screen shot 2016-08-08 at 11 20 00](https://cloud.githubusercontent.com/assets/869724/17475214/1ce5d830-5d5a-11e6-86d6-a0aa535836f4.png)

**Comment by infograf768** [comment]
Misses `&tmpl=component` in the modals

**Comment by infograf768** [comment]
That's because the EDIT functionnality in fields/modal/various items is not implemented.
They only do Select.

**Comment by andrepereiradasilva** [comment]
If people override the core funcionality they need to do it the core way.
com_associations can't be predict that.

**Comment by andrepereiradasilva** [comment]
reggarding the language string i agree. i can make a PR to change that.

**Comment by infograf768** [comment]
@Bakual 
Thanks for looking at your component. 😺

**Comment by andrepereiradasilva** [comment]
we need more 3º party components to test ...

**Comment by infograf768** [comment]
Missing 
JLoader::register('SermonspeakerHelperRoute', JPATH_SITE . '/components/com_sermonspeaker/helpers/route.php');

See here:
https://github.com/joomla/joomla-cms/pull/11321

**Comment by Bakual** [comment]
@infograf768 You're welcome :smile:

**Comment by infograf768** [comment]
@jreys @andrepereiradasilva 

Please see if we can add `&amp;tmpl=component` when saving Reference or Target for components who do not have the EDIT functionnality in their modals. It is maybe just a matter of checking if it is present or not when using Apply and add it if not.

**Comment by andrepereiradasilva** [comment]
tested the sermons speaker with the latest staging (made a minor commit because of language files).

To make it work, just had to add the tmpl=component thing and typeAlias/associationsContext to the models. example

``` php
public $typeAlias = 'com_sermonspeaker.sermon';
protected $associationsContext = 'com_sermonspeaker.sermon.item';
```

``` php
public $typeAlias = 'com_sermonspeaker.speaker';
protected $associationsContext = 'com_sermonspeaker.speaker.item';
```

``` php
public $typeAlias = 'com_sermonspeaker.serie';
protected $associationsContext = 'com_sermonspeaker.serie.item';
```

(categories were already working)

**Comment by andrepereiradasilva** [comment]
i'm gone close this.
