### ISSUE TITLE
Copy from reference language to associated item feature

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#8]
#### Introduction

This issue is a placeholder for implementation of the copy feature in side by side view.

IMHO, there are two ways to achive this goal.
#### Replicate them edit

Button that uses the controller to replicate the content at DB level and then load it in a edit iframe.
##### Advantages

More easy to implement.
##### Disadvantages

Less flexible. We can only use the copy feature when we want to create a new associated item.
#### Copy field by field with javascript

In this option the button would use a javascript process that would get the values of all fields inside the reference item iframe and they save them in the same fields in the associated item iframe.
##### Advantages

Very flexible. We can use use it to create a new item or overwirte the existing one.
In reality, we could even extend this by adding a mouseover button to each field to copy just that field.
##### Disadvantages

Possible harder to implement, we have to make sure we replicate all the javascript behaviours when the value is changed (ex: showon).

**Comment by infograf768** [comment]
As far as I remember, in Joomfish, we had a Copy button near to each field.

**Comment by andrepereiradasilva** [comment]
yeah, we could do both, copy all and with js inject a button to copya particular field.
But IMHO the priority should be the copy all.

**Comment by andrepereiradasilva** [comment]
closing as we have a PR to test https://github.com/joomla-projects/gsoc16_improved-multi-lingual/pull/104
