### ISSUE TITLE
PR waiting core merge

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-projects/gsoc16_improved-multi-lingual#87]
Just a list of core PR we make that still need to be merged into the core for com_associations to work properly so we can track them.
#### Yet to merge
- JTable alias: https://github.com/joomla/joomla-cms/pull/11623 [?]
#### Merged
- ACL com_contact: https://github.com/joomla/joomla-cms/pull/11503 [3.6.3]
- ACL com_newsfeeds: https://github.com/joomla/joomla-cms/pull/11502 [3.6.3]
- ACL com_weblinks: https://github.com/joomla-extensions/weblinks/pull/255 [3.x]
- Install postgresql typo: https://github.com/joomla/joomla-cms/pull/11532 [3.6.3]
- Use JLoader for the router: https://github.com/joomla/joomla-cms/pull/11321 [3.6.1]
- Use JLoader for the router (weblinks): https://github.com/joomla-extensions/weblinks/pull/247 [3.x]
- Associations tab hide: https://github.com/joomla/joomla-cms/pull/11316 https://github.com/joomla/joomla-cms/pull/11328 [3.6.1]
- Component tpml parameter: https://github.com/joomla/joomla-cms/pull/11220 [3.6.1]
- Menu list issue: https://github.com/joomla/joomla-cms/pull/11355 [3.6.3]
- Menu edit id: https://github.com/joomla/joomla-cms/pull/11525 [3.6.3]
- JTable warning: https://github.com/joomla/joomla-cms/pull/11573 [3.6.3]
- Menu Notice on Save as copy https://github.com/joomla/joomla-cms/pull/11647 [3.6.3]
- Categories Notice on Save as copy https://github.com/joomla/joomla-cms/pull/11664 [3.6.3]
- Menus Modal: https://github.com/joomla/joomla-cms/pull/11471 [Merged in 3.7.0 branch]
- (don't know if there are more)

**Comment by andrepereiradasilva** [comment]
replace by a wiki page https://github.com/joomla-projects/gsoc16_improved-multi-lingual/wiki/PR-waiting-core-merge

**Comment by infograf768** [comment]
there are:
category Notice on save2copy https://github.com/joomla/joomla-cms/pull/11664 (3.6.3)

**Comment by andrepereiradasilva** [comment]
already in the wiki page
