### ISSUE TITLE
Fix ACL problem on update

### ISSUE THREAD

**Issue by jreys** [joomla-projects/gsoc16_improved-multi-lingual#93]
#### Actual result

Right now when updating Joomla to support this new component, ACL is currently broken, it was fixed on install but on update the ACL might be different and we didn't find a general way to do this.
#### Expected result

Have update ACL == install ACL

**Comment by andrepereiradasilva** [comment]
i didn't foun it interely is one idea that can be explored
is using the udpate script to dynamicly update the com_associations ACL
See https://github.com/infograf768/joomla-cms/pull/30/files#diff-e3c745afdbb43914c4f183a8c1587346R1619

**Comment by alikon** [comment]
we need to add com_associations https://github.com/joomla-projects/gsoc16_improved-multi-lingual/blob/staging/administrator/components/com_admin/script.php#L1588
as well

**Comment by alikon** [comment]
already done by my mistake direct commit instead of a new PR
forgive me :worried:

**Comment by andrepereiradasilva** [comment]
np, for small things i do it too

**Comment by andrepereiradasilva** [comment]
closing as we have a RFC to discuss it https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/101
