### ISSUE TITLE
Associations tab not readonly for menu item reference (side by side)

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/gsoc16_improved-multi-lingual#96]
As title says.

**Comment by alikon** [comment]
i'm able to replicate

**Comment by alikon** [comment]
if we apply https://github.com/joomla/joomla-cms/pull/11471 no more bug
i close this

**Comment by andrepereiradasilva** [comment]
i'm going to reoepn this because it was expect to work without https://github.com/joomla/joomla-cms/pull/11471

**Comment by andrepereiradasilva** [comment]
@jreys one more bug to solve

**Comment by andrepereiradasilva** [comment]
closing as we have a PR to test https://github.com/joomla-projects/gsoc16_improved-multi-lingual/issues/102
